apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-my-show
  namespace: khushi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-my-show
  template:
    metadata:
      labels:
        app: book-my-show
    spec:
      containers:
      - name: bms-app
        image: khushijain0910/capstone-project:2
        ports:
        - containerPort: 3000
