apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: khushi
spec:
  type: LoadBalancer
  selector:
    app: book-my-show   # must match the deployment labels
  ports:
    - port: 80          # External port for the LoadBalancer
      targetPort: 3000  # Pod container port

